action = input()
n1 = int(input())
n2 = int(input())
if (action=='*')
  print (n1 * n2)
if (action=='+')
  print (n1 + n2)
if (action=='-')
  print (n1 - n2)
if ((action=='/')&(n2 != 0))
  print (n1 / n2)
if ((action=='/')&(n2 == 0)):
    print ('AMOGUS')
